# Webサイトのタイトル
title = "Work From Dote"

# WebサイトのURL
baseURL = "https://dotechan.github.io/blog/"

# Webサイトのテーマ(https://github.com/ertuil/erblog)
theme = "erblog"

# 絵文字の有効化
enableEmoji = true

# 日本語の文字カウント等を有効化
hasCJKLanguage = true
languageCode = "ja"

# URLのカスタマイズ
[permalinks]
    post = "/:year/:month:/:day/:filename/"

# ドットは裸キーでの使用が禁止されてる
# https://qiita.com/b4b4r07/items/77c327742fc2256d6cbe
[Params]
    portrait = 'self/image/kichi_obusu.JPG'
    author = "dotechan"
    description = "弱々Androidエンジニア"
    bio = "技術的なことから日常のことまで幅広く投稿していきます"

# 画面下部のフッターを追加する
[[menu.footer]]
    identifier = "home"
    url = ""
    name = "home"
    weight = 1

# githubのアイコンを追加する
[[menu.icon]]
    url = "https://github.com/dotechan/"
    name = "github"
    weight = 1
