# Webサイトのタイトル
title = "Work From Dote"

# WebサイトのURL
baseURL = "https://dotechan.github.io/blog/"

# Webサイトのテーマ(https://github.com/ertuil/erblog)
theme = "erblog"

# 絵文字の有効化
enableEmoji = true

# 日本語の文字カウント等を有効化
hasCJKLanguage = true
languageCode = "ja"

# ドットは裸キーでの使用が禁止されてる
# https://qiita.com/b4b4r07/items/77c327742fc2256d6cbe
[Params]
    portrait = 'self/image/kichi_obusu.JPG'
    author = "dotechan"
    description = "社会人5年目"
    bio = "日常や勉強したことをダラダラと書いていきます"

# 画面右上のメニューを追加する
[[menu.main]]
    url = "/zone/"
    name = "Zone"
    weight = 1

# 画面下部のフッターを追加する
[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

# githubのアイコンを追加する
[[menu.icon]]
    url = "https://github.com/dotechan/"
    name = "github"
    weight = 1
