---
title: "2021年の振り返り"
description: "2021年の振り返り"
date: 2021-12-31T22:12:09+09:00
categories: ["技術"]
tags: ["振り返り"]
draft: false
---

= AsciiDoc Writer's Guide
:toc:

## スキル棚卸し

### 業務履歴
* Androidアプリ開発4年6ヶ月
* Webアプリケーション開発12ヶ月

### 振り返り

#### 今年やったこと

月毎に新しく触り始めた技術や注力した技術をTwitterやブログから拾ってきてまとめてみた。 +
並べてみると広く浅く新しいことを始めていた。一方で相変わらず継続できていることはない。 +
このまま行き当たりばったりで何も成し遂げられない、残せずに日々を過ごしていっていいのか？時間は有限であるためそろそろ戦略が必要な気がしている。

* 1月
** 新案件
** HTML/CSS/JS
** React
** Raspberry Pi
* 2月
** AWS(Lambda/API Gateway)
* 3月
** AWS(S3/RDS/CloudFront/Route 53/WAF)
** MySQL
** Twitter開始
* 4月
** 新案件
* 5月
** Spring Boot
** PostgreSQL
* 6月
** ReactNative
* 7月
** 個人開発(DB構築とAPI開発)
* 8月
** データベーススペシャリスト申し込み
** コンパイラ入門
** Docker
* 9月
** データベーススペシャリスト勉強
* 10月
** データベーススペシャリスト受験
* 11月
** Redux
* 12月
** Redux

1月からWebアプリケーション開発を行うPJに異動したことは大きなイベントだった。 +
未経験の領域であり周りについていくためにも全力で技術に向き合うことができた。 +
その中でアウトプットの習慣をつけるためにTwitterを始めたが、これもよかった。自分の言葉でまとめてアウトプットすることで知識を整理できることもいいが、それ以上にインプットツールとして活躍している。 +

#### やりたいこと・なりたい姿
* 身近な人の課題をシステムエンジニアリングを通して解決することができるエンジニア

仮説検証を素早く行うことができるや業務効率化のスクリプトを簡単に実装できる、そんなエンジニアだとかっこいいなと思っていた。 +
最近はその先というか自分の技術を活かして身近な人に喜んでもらうことが自分のモチベであり自分が社会に提供できる価値なのでは？と考えている。 +
業務では長いこと業務アプリケーションの開発に従事しているが、より身近な人が利用しているtoCのアプリケーション開発をしてみたい、具体的には食や健康に関するアプリケーションの開発をしてみたい気持ちがある。 +
個人開発だと継続できない気しかしないので副業(会社の規定で禁止だからバレないとは思うが気は引ける)であったり本業でもチャンスがあれば挑戦したいので上司には意向を伝えてみよう。

### 来年の抱負
* 継続して何かに取り組む