---
title: "ふるさと納税はお得なのか"
description: "ふるさと納税の仕組みと控除についての復習"
date: 2020-09-21T16:20:03+09:00
categories: ["教養"]
tags: ["ふるさと納税", "控除"]
draft: false
---

= AsciiDoc Writer's Guide
:toc:

== はじめに
ふるさと納税でどれくらいお得になるのか？ +
そもそも控除って何？を調べ直してまとめました。

== 参考記事
* https://www.soumu.go.jp/main_sosiki/jichi_zeisei/czaisei/czaisei_seido/furusato/mechanism/[ふるさと納税のしくみ]
* https://advisors-freee.jp/article/category/cat-big-05/cat-small-13/6431/[そもそも「控除」って何？節税になる所得控除、税額控除とは]
* https://biz.moneyforward.com/payroll/basic/difference-resident-tax-income-tax/[所得税と住民税の違いとは？]
* https://dc.daiwa.jp/ideco/column/article_039/[今さら聞けない、ふるさと納税／（3）所得控除と税額控除の違い]

== ふるさと納税とは ==
自分の選んだ自治体に寄付を行った場合に、寄付金額のうち2,000円を越える部分については +
上限の範囲内で所得税と住民税から全額が控除される制度です。 +
イメージとしては2,000円で返礼品を手に入れることができるので、返礼品が2,000円以上の価値であれば +
お得と言うことができます。

都市部に人が集まり、その都市に納税するため、都市部は潤うけど生まれ育った街にはお金が入らない
といった状況を改善するためにできた制度のようです。

== ふるさと納税の手順 ==
1. 寄付する自治体を選ぶ
2. 寄付する
3. 確定申告を行う
4. 所得税からの控除
5. 翌年度の住民税からの控除

1の段階では「楽天ふるさと納税」といったWebサイトから寄付する自治体を選ぶといいでしょう。

2の段階では1で選んだ自治体に寄付する訳ですが、税金から控除されえる額には上限があります。 +
上限は収入によって変わるため、計算サイトで上限を確認した上で寄付するようにしましょう。  +
計算サイトで出た金額はあくまで目安なので *実際の寄付金額は計算サイトで出した上限金額よりも少なめ* にしておきましょう。

3の段階で確定申告を行い、寄付したことを申請することで税金の控除を受けることができます。 +
*ただ寄付しただけでは控除を受けられない* ので、必ず確定申告を行いましょう。 +
確定申告の際は寄付した証明が必要になるので、自治体から受け取った証明書は大切に保管しておきましょう。

NOTE: ワンストップ特例制度が適用できる条件に当てはまるのであれば、ワンストップ特例を利用することで確定申告を行わなくても控除を受け取ることができます。

4,5は3が住んでいれば対応してもらえます。

== 控除とは ==
「一定の金額を差し引く」という意味があります。 +
税金の控除では大きく「所得控除」と「税額控除」があります。 +
所得控除は課税される所得金額を減らすことができます。 +
税額控除は税額自体を減らすことができます。所得控除よりも節税効果が高いです。

収入 - 必要経費 = 所得金額 +
所得金額 - *所得控除* = 課税所得金額 +
課税所得金額 × 税率 = 税額 +
所得税額 = 税額 - *税額控除* +

ふるさと納税の控除は所得控除と税額控除の組み合わせであり、最終的に2,000円を越える寄付額分の +
税額控除が受けられる制度になります。 +
ただ税金を納めるよりも2,000円以上の価値のある返礼品を受け取れるためお得と言えます。

== まとめ ==
* 2,000円以上の価値がある返礼品をもらえるのであれば、ふるさと納税をした方がお得
* 控除を受けたいのであれば、寄付の証明書を保管し、確定申告をしよう
