---
title: "賃貸物件の退去時にぼったくられないように"
description: "退去時の敷金の返済について"
date: 2020-08-28T18:40:11+09:00
categories: ["教養"]
tags: ["賃貸", "不動産"]
draft: false
---

= AsciiDoc Writer's Guide
:toc:

== はじめに
入居時にボラれたのを機に退去時にボラれないように知識武装している最中です。 +
退去時に不当な金額を請求されないためにも、退去時の注意点をまとめておきます。

== 参考
* https://www.youtube.com/watch?v=eFAggPtAV1A&list=WL&index=8&t=0s[第136回【ほぼ無料に出来る】賃貸物件の退去費用をとことん安くする方法【お金の勉強 初級編】]

* https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk3_000020.html[「原状回復をめぐるトラブルとガイドライン」について]

== 結論
* 契約締結時に退去時の費用についても確認して決めておくことでトラブルを避ける
* 契約時の特約に記載されていても全てを鵜呑みにする必要はないので交渉する
* 納得できない場合は絶対にサインしない。困った時はNPOや専門家の意見を聞く

== 内容
=== 契約締結時の注意
契約書の特約の蘭に「ハウスクリーニング費用は賃借人が負担する」など記載されている +
ケースがあります。ちなみに私は記載されていました。 +
ガイドラインに従うと賃借人が退去時に支払うお金賃借人の故意・過失、善管注意義務違反の +
損耗・毀損を復旧するための費用だけです。 +
経年劣化などによる損耗は月々の賃料に含まれており、賃貸人が復旧すべきです。 +
ただ、ガイドラインには賃借人と賃貸人の間で納得できていれば賃借人にも損耗の +
請求ができることになっています。 +
それをいいことに特約に賃借人が不利になる内容をここぞとばかりに記載されてしまうようです。 +

契約時に特約に納得できない場合はガイドラインを用いて交渉しておくべきでしょう。

=== ガイドライン
退去時のトラブルは2020年現在、年々増加しています。 +
そこで現状回復の定義やトラブル時のQ&A、裁判の事例などがガイドラインとして打ち出されています。 +

現状回復は「賃借人が借りた当時の状況に戻すこと」でないことも記載されています。 +
絶対に賃貸物件の契約前・退去前に目を通しておくべきです。

=== 特約の効力
特約を見逃していてサインしてしまったので、なくなく請求されたハウスクリーニング代を +
払うしかない、というわけでもないようです。 +
明細を確認し、不当な請求であると感じた場合は交渉・専門家への相談をしましょう。 +

そもそも、特約としての以下3つを満たしていないと特約としての効力もないようです。 +

. 具体的な金額が書かれている
. 契約者が内容を理解している
. 特約のページに各押印がされている

上記が満たされているかも確認しておくとよいでしょう。

=== 専門家への相談
「賃貸トラブルたすけ隊」という団体がおすすめのようです。 +
ガイドライン的には賃借人が負担すべき内容ではないけど、しれっと特約に記載されていて +
サインまでしてしまっている、といった場合でも不当であると感じた場合は相談してみます。

=== まとめ
入居時だけでなく退去時もぼったくられるなんて悲しいですね。 +
不動産業界の闇を感じますが、知識や情報を持っていないと損をするというのは +
賃貸物件を借りる時だけには限らないので、正しい知識を仕入れるようにしないと。
