---
title: "NISAとは"
description: "NISAとつみたてNISAについて"
date: 2020-10-16T08:38:37+09:00
categories: ["教養"]
tags: ["NISA", "つみたてNISA", "非課税"]
draft: false
---

= AsciiDoc Writer's Guide
:toc:

== はじめに
インデックス投資を始めるにあたり、お得になると言われているNISAについて調べました。 +
小額から始めるインデックス投資であれば、つみたてNISAを利用することで +
節税できることがわかったので利用していこうと思います。


== 参考記事
* https://www.youtube.com/watch?v=QMkyAS4IKuA[第7回 NISAと積立NISAって何？【お金の勉強 株式投資編】]
* https://www.fsa.go.jp/policy/nisa2/about/index.html[NISAとは？]
* https://www.rakuten-sec.co.jp/nisa/rule.html[楽天証券 取引ルール]

== NISAとは
「NISA口座」内で、毎年一定金額の範囲内で購入した金融商品から得られる利益(売却益や配当)が非課税になる制度のこと。 +
イギリスのISA(Indivisual Savings Account)をモデルにした日本版なのでNISAという愛称がついている。

=== NISAとつみたてNISAの比較

[cols="3*, options="header"]
|=====================================================================
| 比較項目   | NISA    | つみたてNISA

| 非課税対象 | 配当金・分配金や譲渡益   | 分配金や譲渡金(*1)
| 口座開設可能数    | 1人1口座  | 1人1口座  
| 非課税投資枠  | 毎年120万円まで   | 毎年40万円まで
| 非課税期間    | 最長5年   | 最長20年(*2)
| 投資可能期間  | 2014~2023年   | 2018~2037年
| 損益通算(*3)  | できない  | できない
|=====================================================================
(*1) つみたてNISAの対象商品は、手数料が低水準、頻繁に分配金が支払われないなど、長期・積立・分散投資に適した公募株式投資信託と上場株式投資信託（ETF)に限定されている +
(*2) ロールオーバー不可能(翌年の非課税投資枠に充てることができない) +
(*3) NISA以外の口座からNISA口座で出た損失と相殺して税金の控除を受けたりできない

== 疑問

=== NISAとつみたてNISAをそれぞれ開設できるか
できない。 +
NISAかつみたてNISAのどちらかを選択することになる。 +
ただ、年単位でNISAとつみたてNISAを切り替えることはできる。

=== 1人に対して1NISA口座か？1証券口座に対して1NISA口座か
1人に対して1NISA口座になる。 +
証券会社によって取り扱っている金融商品が異なるため、証券口座の切り替えはできる。 +
配偶者は別途NISA口座を開設できる。

=== 非課税期間が満了した金融資産はどうなるか
ロールオーバーするか課税口座である特定口座または一般口座へ払い出すことになる。 +
つみたてNISAではロールオーバーできないので課税口座に今まで非課税だった金融資産を +
うつすことになるでしょう。

=== NISAの非課税投資枠を超えた買付はできるのか
証券会社によって振る舞いは変わります。以下は楽天証券の例です。

....
NISA買付可能額を超過したと判定される約定については、特定口座を開設されている場合は特定口座への預託となり、特定口座を開設されていない場合は一般口座への預託となります
....
とあるので買付はできますが、当然NISAのメリットである非課税の恩恵は受けられない。

....
積立設定によるNISA取引については、あらかじめ定められた日の注文時にNISA買付可能額の超過を判定いたします。なお、注文時にその年のNISA買付可能額を超過したと判定された場合は、その注文は執行されません。
....
とあるのでNISA買付可能額の範囲内で買付できるようです。
