---
title: "賃貸物件を借りた時に10万円ぼったくられた話"
description: "賃貸物件を借りるに当たって事前に知っておきたかったこと"
date: 2020-08-20T20:29:58+09:00
categories: ["教養"]
tags: ["賃貸", "不動産"]
draft: false
---

= AsciiDoc Writer's Guide
:toc:

== はじめに
人生二回目の引越しを決意し賃貸物件を借りたのですがボラれました。 +
今回は勉強料だと割り切って次回の引越しで同じ過ちを犯さないように +
備忘録として記事を残しておきます。 +
誰かの参考になると嬉しいけど、このブログは誰も見てないか😂 +
土手から引っ越しちゃうしブログのタイトルも変えないとだな😂

== 参考動画
* https://www.youtube.com/watch?v=guYWHR2-_P8&list=WL&index=17&t=0s[第135回【10万円以上安くできる】賃貸物件をお得に借りるテクニックまとめ【保存版】【お金の勉強 初級編】]

== 結論
* 良い業者を見つけよう
* 相見積もりをとろう
* やりとりは口頭ではなくメールで
* 仲介手数料は入居者に対して家賃(共益費を除く)の50%までしか請求できない
* ハウスクリーニングは不要
* 火災保険は自分で選ぶ。2年で2万円以上のものは論外
* 安心サポートも不要

== 動画の内容
=== 良い業者を見つける
入居者 -> 仲介業者 -> 管理会社 -> オーナーという流れで関わることになるが +
中抜きで仲介業者や管理会社が不要なオプションを増し増しにしてぼったくることが多い。 +
デフォルトは全部載せなので必ず相見積もりを取り、良い業者を見つけるようにする。

=== 仲介手数料は家賃の0.525ヶ月分まで
法律で入居者に対して請求していい仲介手数料は家賃の0.525ヶ月分までと決められている。 +
仲介業者はオーナーからも仲介手数料をもらっており、入居者に対しては請求しない業者も +
あるのでやはり良い業者を見つけるべき。

=== ハウスクリーニングは不要
どこの会社も適当にスプレーふるだけだと思っていればいい。 +
内覧して綺麗だったはずだし、ハウスクリーニングは不要である。
退去時に取られるパターンもありますが、オーナーが支払うというのが +
ガイドラインに記載されているようなので交渉して外してもらうべきポイントです。

=== 火災保険は自分で選ぶ
2年で2万以上の保険はぼったくり。 +
加入が義務付けられていたとしても保険の種類は自分で選べる。 +
それにオーナーも火災保険に入っていて、設備の修理などはオーナーの責務である。 +
年間4,000円ほどで十分な保証の火災保険に加入することができる。 +

=== 安心サポートも不要
室内の見守りサポートは火災保険で十分カバーできる。 +
設備の保険はオーナーの責務なので入居者に課せられる義理はない。

== 自分の契約を振り返って
=== 仲介手数料
家賃の0.5ヶ月分でした。 +
仲介手数料は家賃1ヶ月分が相場だと思い込んでいたのでお得に感じていましたが +
法律で定められている上限をきっちり取られているだけでした。😂

=== ハウスクリーニング
退去時に取られるパターンで約50,000円でした。。 +
ガイドラインではオーナーが支払うことになっているそうなのでやっちまいました。。 +
特約に書かれていたので外してもらうように交渉すべきでした。

=== 火災保険
2年間で24,300円でした。。完全にやられてますね。。 +
現在解約すれば21,000円は返ってくるので早急に解約します。 +
クーリングオフ適用できないか見てみましたが、クーリングオフは契約開始日ではなく +
契約申込日から8日以内だったため適用できそうにありませんでした。😭 +
参考動画の30:00あたりの保険を調べつつ自分に合った保険を探します。

=== 安心サポート
保証会社の契約とセットになっているようで単体で外せるのかわかりません。。 +
鍵受け渡し時に不動産会社に確認してみますが難航しそうだな。。

== まとめ
ハウスクリーニングと火災保険と安心サポートで10万近くぼったくられてるな。。 +
動画を見た後に悲しくなり怒りが湧いてきました。😂 +
損しないためにも知識武装することが重要だと改めて感じました。
