---
title: "macOSでのAOSPビルド環境の構築"
description: "macOSでAOSPのフルビルドからエミュレータでの実行までの記録"
date: 2020-10-02T00:11:04+09:00
categories: ["技術"]
tags: ["AOSP", "macOS"]
draft: true
---

= AsciiDoc Writer's Guide
:toc:

== はじめに
AOSPのソースコードはCode SearchというWebサイトから確認できます。 +
ただ、使い慣れているAndroid Studioで確認できた方がソースコードを追いやすいだろうと考え、ローカルでAndroid Studioでソースコードを確認する方法を調べました。

== 環境

* Mac OS X(10.15.6)

== 参考記事
* https://source.android.google.cn/setup/build/initializing?hl=ja#top_of_page[ビルド環境を構築する]
* https://github.com/aosp-mirror/platform_development/tree/master/tools/idegen[github公式リポジトリ]
* https://android.benigumo.com/tag/lsopenurlswithrole/[アイコン叩いても何も反応しない Android Studio]
* https://developer.android.com/studio/intro/studio-config[Android Studio の設定]
* http://effie.io/opening-aosp-with-intellij-part-3/[Opening AOSP with IntelliJ - part 3]
* https://medium.com/@christopherney/building-android-o-with-a-mac-da07e8bd94f9[Building Android O with a Mac]
* https://qiita.com/seri_k/items/e978c1339ce51f13e297[MacでのJAVA_HOME設定]

== 順序

=== ディスクイメージの作成
ディスクイメージ(.dmgファイル)とは、マウント可能なディスクやボリュームのように表示され、動作するファイルのこと。 +
ディスクユーティリティまたはhdiutilを使用して作成することができる。

link:https://source.android.google.cn/setup/build/initializing?hl=ja#setting-up-a-mac-os-x-build-environment[reference]に従ってAOSPのソースコードをダウンロード先にあたる +
大文字・小文字が区別されるファイルシステムを作成します。

以下のコマンドでファイルシステムを作成します。 +
[source]
````
hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 250g ~/android.dmg.sparseimage 
````

スパースイメージにしておくことで後からディスクイメージのサイズを変更することができます。

ディスクイメージのマウント・アンマウントはヘルパー関数をbash_profileに追加しておくとよいでしょう。
[source]
````
# mount the android file image
mountAndroid() { hdiutil attach ~/android.dmg.sparseimage -mountpoint /Volumes/android; }
# unmount the android file image
umountAndroid() { hdiutil detach /Volumes/android; }
````

=== AOSPのソースコードをダウンロード
https://source.android.google.cn/setup/build/downloading?hl=ja


=== jdk1.8をダウンロード
MacOSにプリインストールされていたJDKのバージョンが14だったので以下から8をダウンロードしました。

https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

=== Android Studioの設定を変更
RAMの量とか

=== トラブルシューティング

Android Studioのアイコンを押しても起動しない
studio.vmoptionsの設定ファイルに不正な文字列が混ざっていたためAndroid Studioが読み込めず起動していませんでした。
https://android.benigumo.com/tag/lsopenurlswithrole/


ディスク容量が足りない
....
error: file write error (No space left on device)
....
dmgファイルの容量が不足している
リファレンスにも空き容量を増やすには、ディレクトリを削除して作成しなおすとある。
aosp用に作成したdmgファイルを削除する
dmg上で作成したディレクトリをrmで削除しようとするとbusyで削除できなかったので、dmgを削除している。

ito-hi@MacBook-Pro aosp % tar -zxvf google_devices-sargo-pd2a.190115.029-338f4e68.tgz
x extract-google_devices-sargo.sh

合意した後

x vendor/
x vendor/google_devices/
x vendor/google_devices/sargo/
x vendor/google_devices/sargo/BoardConfigPartial.mk
x vendor/google_devices/sargo/device-partial.mk
x vendor/google_devices/sargo/proprietary/
x vendor/google_devices/sargo/proprietary/vendor.img
x vendor/google_devices/sargo/android-info.txt
x vendor/google_devices/bonito/
x vendor/google_devices/bonito/proprietary/
x vendor/google_devices/bonito/proprietary/device-vendor.mk
x vendor/google_devices/bonito/proprietary/BoardConfigVendor.mk

ito-hi@MacBook-Pro aosp % lunch aosp_sargo-eng

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_sargo
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_OS=darwin
HOST_OS_EXTRA=Darwin-19.6.0-x86_64-10.15.7
HOST_BUILD_TYPE=release
BUILD_ID=RP1A.201105.002
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/google/bonito hardware/google/av hardware/google/camera hardware/google/interfaces hardware/google/pixel hardware/qcom/sdm845 vendor/google/camera vendor/qcom/sdm845 vendor/google/interfaces
============================================


https://e-tec-memo.herokuapp.com/article/192/
https://linuxhint.com/linux_ulimit_command/

手順書にはstack sizeは1024に変更とあるが、"glob: fcntl: too many open files"と警告が出たので8092に設定した
ito-hi@MacBook-Pro ~ % ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       5568
-n: file descriptors                8192



FAILED:
In file included from build/make/core/main.mk:1327:
build/make/core/Makefile:49: error: VINTF metadata found in PRODUCT_COPY_FILES: vendor/qcom/sargo/proprietary/compatibility_matrix.xml:system/compatibility_matrix.xml:qcom, use vintf_fragments instead!.
22:30:37 ckati failed with: exit status 1

フレームワーク互換性マトリクス(vendor/qcom/sargo/proprietary/compatibility_matrix.xml)は存在するが、対応するプロダクト互換性マトリクス(system/compatibility_matrix.xml)が存在しないように見える

PRODUCT_COPY_FILESをLOCAL_VINTF_FRAGMENTSに修正
→成功
(参考)https://source.android.google.cn/devices/architecture/vintf/objects?hl=ja#manifest-fragments


エミュレータが立ち上がらない
ito-hi@MacBook-Pro aosp % emulator
emulator: WARNING: encryption is off
qemu-system-aarch64: Could not open '/Volumes/android/aosp/out/target/product/sargo/userdata-qemu.img': No such file or directory

https://developer.android.com/studio/run/emulator-commandline?hl=ja#system-filedir
data/パーティションのイメージがないと言われている模様
→userdata.imgも存在しないからuserdata-qemu.imgも作成されない？userdata.imgがない理由を調べて、わからなければuserdata-qemu.imgを作成してしまうか？
→すでに存在する~/.android配下のuserdata.imgを利用してもいいかも？
→パーティションのリサイズでダメだった
````
ito-hi@MacBook-Pro aosp % emulator -data ~/.android/avd/Pixel_3a_API_29.avd/userdata.img
emulator: WARNING: userdata partition is resized from 1 M to 800 M

ERROR: resizing partition e2fsck failed with exit code 8
emulator: WARNING: encryption is off
emulator: emulator window was out of view and was recentered
````

fatal error: error in backend: IO failure on output stream: No space left on device
02:03:26 ninja failed with: exit status 1

#### failed to build some targets (03:06:49 (hh:mm:ss)) ####

hdiutil resize -size <new-size-you-want>g ~/android.dmg.sparseimage
<new-size-you-want>を600にした



#### build completed successfully (02:13:13 (hh:mm:ss)) ####

ito-hi@MacBook-Pro aosp % emulator
emulator: INFO: boot completed
emulator: INFO: boot time 53902 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.
emulator: WARNING: Not saving state: RAM not mapped as shared

https://source.android.com/setup/create/avd?hl=ja
x86 64ビットのAVDをビルドする
lunch sdk_phone_x86_64